//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------------ Functions -------------------------

// Address range: 0x100003f50 - 0x100003f85
int main(int argc, char ** argv) {
    // 0x100003f50
    int64_t v1; // bp-28, 0x100003f50
    _scanf("%d", &v1);
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// int scanf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gc
// Detected functions: 1
